ToontownStart: Polling for game2 to finish...
INJECTOR ENABLED
ToontownStart: Game2 is finished.
ToontownStart: Starting the game.
ToontownStart: setting default font
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
ToontownStart: Loading default gui sounds
ToontownStart: serverVersion:  sv0.0.0.1-dev
{401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x1286A468>}
local
fisherman origin:  render/scene/toontownCentral/2000:safe_zone/fishing_pond_1/npc_fisherman_origin_0
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\lib\lib-tk\Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "toontown\toonbase\DevInjector.py", line 3, in runInjectorCode
    exec (text.get(1.0, "end"),globals())
  File "<string>", line 5, in <module>
ImportError: cannot import name CLIENT_SET_AVATAR
Exception occurred while processing Func-createAvatarAndAvList-26 of Sequence-211:
Sequence-211:
  0.000 Sequence-211 {
  0.000   *Func-createAvatarAndAvList-26
  0.000   Wait dur 1
  1.000   *Func-createAvatarNPCBot-27
  1.000   Wait dur 1
  2.000   *Func-deleteCreatedAvatar-28
  2.000   Wait dur 1
  3.000 }

Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\direct\showbase\ShowBase.py", line 1801, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.9.0\python\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.9.0\python\direct\interval\IntervalManager.py", line 124, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
  File "C:\Panda3D-1.9.0\python\direct\interval\MetaInterval.py", line 518, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.9.0\python\direct\interval\MetaInterval.py", line 494, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.9.0\python\direct\interval\Interval.py", line 207, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.9.0\python\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
  File "<string>", line 11, in createAvatarAndAvList
AttributeError: 'ToontownClientRepository' object has no attribute 'sendCreateAvatarMsg'
Traceback (most recent call last):
  File "otp\otpbase\OTPBase.py", line 238, in run
    taskMgr.run()
  File "C:\Panda3D-1.9.0\python\direct\task\Task.py", line 502, in run
    self.step()
  File "C:\Panda3D-1.9.0\python\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "C:\Panda3D-1.9.0\python\direct\showbase\ShowBase.py", line 1801, in __ivalLoop
    IntervalManager.ivalMgr.step()
  File "C:\Panda3D-1.9.0\python\direct\interval\IntervalManager.py", line 96, in step
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.9.0\python\direct\interval\IntervalManager.py", line 124, in __doPythonCallbacks
    self.ivals[index].privPostEvent()
  File "C:\Panda3D-1.9.0\python\direct\interval\MetaInterval.py", line 518, in privPostEvent
    self.__doPythonCallbacks()
  File "C:\Panda3D-1.9.0\python\direct\interval\MetaInterval.py", line 494, in __doPythonCallbacks
    ival.privDoEvent(t, eventType)
  File "C:\Panda3D-1.9.0\python\direct\interval\Interval.py", line 207, in privDoEvent
    self.privInstant()
  File "C:\Panda3D-1.9.0\python\direct\interval\FunctionInterval.py", line 88, in privInstant
    self.function(*self.extraArgs, **self.kw)
  File "<string>", line 11, in createAvatarAndAvList
AttributeError: 'ToontownClientRepository' object has no attribute 'sendCreateAvatarMsg'
